name: recorderphone_ui
description: RecorderPhone Flutter UI (template)
publish_to: "none"
version: 0.1.1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.5
  recorderphone_android_usage:
    path: ../packages/recorderphone_android_usage
  shared_preferences: ^2.3.2
  sqflite: ^2.4.2
  system_tray: ^2.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  sqlite3_flutter_libs:
    path: ../third_party/sqlite3_flutter_libs

flutter:
  uses-material-design: true
  assets:
    - assets/tray.ico
